config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root to: "posts#index"
  resources :users, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :locations
  resources :property_types

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_profile
	
	def show
		@the_user = User.find(params[:id])
		@user_profile = @the_user.profile
	end
	def edit

	end
	def update
		if @profile.update(profile_params)
			redirect_to @profile, notice: 'Profile updated successfully'
		else
			render 'edit'
		end
	end

	private

	def find_profile
		@profile = Profile.find(current_user.profile.id)		
	end

	def profile_params
		params.require(:profile).permit(:first_name, :last_name, :phone, :email, :address)
	end
end

app/views/profiles/edit.html.erb
<div class="container-min">
	<h2>Edit profile</h2>

	<%= form_for(@profile) do |f| %>
		<div class="form-group">
			<%= f.label :first_name, "First Name" %>
			<%= f.text_field :first_name, placeholder: "First name", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :last_name, "Last Name" %>
			<%= f.text_field :last_name, placeholder: "Last name", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :phone, "Phone Number" %>
			<%= f.text_field :phone, placeholder: "Phone", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :email, "Email Address" %>
			<%= f.text_field :email, placeholder: "Email", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :address, "Address" %>
			<%= f.text_area :address, placeholder: "Address", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.submit "Update Your profile", class: "btn btn-lg btn-block btn-primary" %>
		</div>
	<% end %>
</div>

app/views/profiles/show.html.erb
<h2>Show Profile</h2>
<p>
	user Id <%= @user_profile.first_name %>
<br>
	username <%= @the_user.username %>
</p>
<div class="user-profile">
	<div class="row">
		<div class="col-sm-3">
			<div class="profile-img">
				<i class="fa fa-user"></i>
				<p class="edit-profile">
				<%= link_to "Edit profile", edit_profile_path(@profile), class: "btn btn-sm btn-info" %>
				</p>
			</div>
			<p class="text-center">
				<i class="fa fa-clock-o"></i> <em>Last login: <%= time_ago_in_words(current_user.current_sign_in_at) %> ago</em>
			</p>
			<% if current_user.role_id.present? %>
				<p class="text-center">
					<%= current_user.role.name.capitalize %>
				</p>
				<% if current_user.role_id == 4 %>
				<p class="text-center">
					<%= link_to "Show user lists", users_path, class: "btn btn-sm btn-success" %>
				</p>
				<% end %>
			<% end %>
		</div>
		
		<div class="col-sm-9">
			<h4>
				<% if @user_profile.first_name.present? || @user_profile.last_name.present? %>
					<%= @user_profile.first_name.capitalize + " " + @user_profile.last_name.capitalize %>
				<% else %>
					<%= @the_user.username.upcase %>
				<% end %>
				<span class="label label-success label-sm"><%= @user_profile.user.posts.count %> <%= (@user_profile.user.posts.count > 1) ? "posts" : "post" %></span>
			</h4>
			<hr>
			<div class="profile-info">
				<div class="panel panel-primary">
					<div class="panel-heading">
						Contact Info
					</div>
					<div class="panel-body">
						<ul>
							<li><i class="fa fa-home"></i> <%= @user_profile.address.present? ? @user_profile.address : "N/A" %></li>
							<li><i class="fa fa-phone"></i> <%= @user_profile.phone.present? ? @user_profile.phone : "N/A" %></li>
							<li><i class="fa fa-envelope"></i> <%= @user_profile.email.present? ? @user_profile.email : "N/A" %></li>
							
						</ul>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>