config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root to: "posts#index"
  resources :users, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :locations
  resources :property_types

end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
	before_action :find_property, only: [:edit, :update, :destroy]
  def index
  	@properties = PropertyType.all.order("property_name ASC")
  end

  def show
  	@posts_by_property = PropertyType.find(params[:id]).posts
  end

  def new
  	@property =PropertyType.new
  end

  def create
  	@property = PropertyType.new(property_params)
  	if @property.save!
  		redirect_to property_types_path
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @property.update(property_params)
  		redirect_to property_types_path, notice: "You have successfully updated property."
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@property.destroy
  	redirect_to property_types_path
  end

  private

  def find_property
  	@property = PropertyType.find(params[:id])
  end

  def property_params
  	params.require(:property_type).permit(:property_name)
  end
end

app/helpers/property_types_helper.rb
module PropertyTypesHelper
end

app/views/property_types/_form.html.erb
<div class="container-min">
	<%= form_for(@property) do |f| %>
		<div class="input-group">
			<%= f.text_field :property_name, class: "form-control", placeholder: "Property type name" %>
			<div class="input-group-btn">
				<% if @property.new_record? %>
					<%= f.submit "Add property", class: "btn btn-success" %>
				<% else %>
					<%= f.submit "Update", class: "btn btn-primary" %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/property_types/edit.html.erb
<%= render 'form' %>

app/views/property_types/index.html.erb
<h2>Property types list</h2>
<div class="container-min table-responsive">
	<table class="table table-bordered">
		<tr>
			<th>Property name</th>
			<th colspan="2">Actions</th>
		</tr>
		<% @properties.each do |property| %>
		<tr>
			<td><%= property.property_name %></td>
			<td><%= link_to "Edit", edit_property_type_path(property) %></td> 
			<td><%= link_to "Delete", property, method: :delete, data: {confirm: "Are you sure?"} %></td>
		</tr>
		<% end %>
	</table>
</div>
<div class="container-min">
	<%= link_to "Add property type", new_property_type_path %>
</div>

app/views/property_types/new.html.erb
<h1>Add property type</h1>
<%= render 'form' %>

app/views/property_types/show.html.erb
<h1>PropertyTypes#show</h1>
<% if @posts_by_property.count > 0 %>
	<% @posts_by_property.each do |post| %>
		<div class="col-sm-6 col-md-3">
			<div class="post-box">
				<div class="img-container">
					<%= link_to post do %>
						<%= image_tag post.image.url(:medium), class: "img-responsive" %>
					<% end %>
				</div>
				<hr>
				<div class="post-text">
					<p class="post-title">
						<% $title = truncate(post.title, length: 50) %>
						<%= link_to $title , post %>
					</p>
					<div class="wrapper-text clearfix">
						<div class="left-box">
							<span class="label label-success"><%= post.post_type.capitalize %></span> 
							<span class="date label label-primary"><i class="fa fa-clock-o"></i> <%= post.created_at.strftime("%b / %d") %></span> 
						</div>
						<div class="right-box">
							<span class="money label label-danger"><i class="fa fa-usd"></i> <%= post.price %></span>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
<% else %>
	<p class="alert alert-warning">There is no post to show.</p>
<% end %>