config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root to: "posts#index"
  resources :users, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :locations
  resources :property_types

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    belongs_to :property_type
    belongs_to :location
    has_many :photos
    has_one :amentity
    has_attached_file :image, styles: { medium: "500x320#",croppable: '560x420', thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true

    def self.search(location, post_type, keyword)
	   where("CAST(location_id As Text) like ? and CAST(post_type As Text) like ? and title like ?",
             "%#{location}%", "%#{post_type}%", "%#{keyword}%") 
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]
  # GET /posts
  # GET /posts.json
  def index
    if params[:location] || params[:post_type] || params[:keyword]
      @posts = Post.search(params[:location], params[:post_type], params[:keyword]).paginate(:page => params[:page], :per_page => 1).order("created_at DESC")
    else
      @posts = Post.where(:enabled => true).paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @image = @post.image.present?
    @posts = Post.all.limit(3).order("created_at DESC")
    @get_amentities = @post.amentity_ids 

    # For development
    if Rails.env.development?
      @amentity_to_array = @get_amentities.gsub!(/[\[\]\"]/, "")
      @amentities = @amentity_to_array.split(/,/)
      @post_amentities = @amentities
    else
      @post_amentities = @get_amentities
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
    
  end

  # GET /posts/1/edit
  def edit
    @get_amentities = @post.amentity_ids 
    if Rails.env.development?
      @amentity_to_array = @get_amentities.gsub!(/[\[\]\"]/, "")
      @amentities = @amentity_to_array.split(/,/)
      @int_amentities = @amentities.map(&:to_i)
    else
      @int_amentities = @get_amentities
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :post_type,:image, :size, :bathroom, :bedroom, :floor, :area, :address, :description, :price,:enabled, :property_type_id, :location_id, :amentity_ids => [], photos_attributes: [:id, :image,  :_destroy])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container-post">
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
        <%= f.label :post_type, "Type" %>
         <%= f.select :post_type, options_for_select([['Sale', 'sale'], ['Rent', 'rent']], @post.post_type), {}, class: "form-control" %>
        </div>
        
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <%= f.label :property_type_id, "Property Type" %>
          <%=f. select :property_type_id, options_from_collection_for_select(PropertyType.all, :id, :property_name, @post.property_type_id), {}, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <h4 class="text-center">Location</h4>
      <hr>
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :location_id, "Province/City" %>
          <%=f. select :location_id, options_from_collection_for_select(Location.all, :id, :name, @post.location_id), {}, class: "form-control" %>
        </div>
      </div>
      
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :area, "Area" %>
           <%= f.text_field :area, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-12 form-group">
        <%= f.label :address, "Address" %><br>
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>

    <div class="row form-group">
      <h4 class="text-center">Amentities</h4>
      <hr>
        <%= f.collection_check_boxes :amentity_ids, Amentity.all, :id, :name, checked: @int_amentities do |cb| %>
          <div class="col-md-4 col-xs-6 checkbox-list">
            <div class="checkbox checkbox-primary">
              <%= cb.check_box %>
              <%= cb.label %>
            </div>
          </div>
        <% end %>
    </div>
    <div class="row">
      <h4 class="text-center">Details</h4>
      <hr>
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :post_type, "Bedrooms" %>
           <%= f.select :bedroom, options_for_select((1..10), @post.bedroom), {include_blank: true}, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :post_type, "Bathrooms" %>
           <%= f.select :bathroom, options_for_select((1..10), @post.bathroom), {include_blank: true}, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :floor, "Floors" %>
           <%= f.select :floor, options_for_select((1..10), @post.floor), {include_blank: true}, class: "form-control" %>
        </div>
      </div>
       <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :size, "Area size" %>
           <%= f.text_field :size, class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :price %>
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">$</span>
            <%= f.text_field :price, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :image, "Featured image" %>
      <div class="form-control">
        
        <%= f.file_field :image %>
      </div>
    </div> 
      <%= f.fields_for :photos do |photo| %>
        <%= render 'photo_fields', f: photo %>
      <% end %>
      <div class="links form-group">
        <%= link_to_add_association ' add images', f, :photos, class: "fa fa-picture-o" %>
      </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
        <div class="checkbox-inline checkbox checkbox-success">
          <%= f.check_box :enabled %>
          <%= f.label :enabled %>
        </div>
        
      </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %> 
</div>

app/views/posts/_photo_fields.html.erb
<div class="nested-fields">
<div class="row form-group">
	<div class="col-sm-10">
		<%= f.file_field :image %>
	</div>
	<div class="col-sm-2">
		<%= link_to_remove_association " remove", f, class: "fa fa-trash" %>
	</div>
</div>


</div>

app/views/posts/_search.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    Search Items
  </div>
  <div class="search-area panel-body">
    <%= form_tag(posts_path, method: "get") do %>      
        <div class="form-group">
            <%= label :location, "Location" %>
            <%= select_tag :location, content_tag(:option,'Select Location',:value=>"") + options_from_collection_for_select(Location.all, :id, :name, params[:location]), class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label :post_type, "Type" %>
         <%= select_tag :post_type, content_tag(:option,'Select Type',:value=>"") + 
                        options_for_select([['Sale', 'sale'], ['Rent', 'rent']], params[:post_type]), 
                        class: "form-control" %>
        </div>    
        <div class="form-group">
          <%= text_field_tag :keyword, params[:keyword], class: "form-control", placeholder: "Search Posts" %>
        </div>
        <div class="form-group">
          <%= submit_tag "Search", class: "btn btn-info btn-block", :name => nil %>
        </div>
      
        <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="home-container">
	<div class="home-slider">
		<%= render 'layouts/slider' %>
	</div>
	<h2 class="text-center">Listing Posts</h2>
	<hr>
	<div class="row">
		<div class="col-md-3">
			<%= render 'search' %>
		</div>
		<div class="col-md-9">
			<% if @posts.count > 0 %>
				<% @posts.each do |post| %>
					<div class="col-sm-6 col-md-4">
						<div class="post-box">
							<div class="img-container">
								<%= link_to post do %>
									<%= image_tag post.image.url(:medium), class: "img-responsive" %>
								<% end %>
							</div>
							<hr>
							<div class="post-text">
								<p class="post-title">
									<% $title = truncate(post.title, length: 50) %>
									<%= link_to $title , post %>
								</p>
								<div class="wrapper-text clearfix">
									<div class="left-box">
										<span class="label label-success"><%= post.post_type.capitalize %></span> 
										<span class="date label label-primary"><i class="fa fa-clock-o"></i> <%= post.created_at.strftime("%b / %d") %></span> 
									</div>
									<div class="right-box">
										<span class="money label label-danger"><i class="fa fa-usd"></i> <%= post.price %></span>
									</div>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			<% else %>
				<p class="alert alert-warning">There is no post to show.</p>
			<% end %>
			<div class="col-xs-12">
				<div class="text-center">
					<%= will_paginate %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<h2 class="text-center">New Post</h2>
<hr>
<div class="container-post">
	<%= render 'form' %>
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'search' %>
  </div>
  <div class="col-md-9">
    <ol class="breadcrumb">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to @post.property_type.property_name, property_type_path(@post.property_type.id) %></li>
      <li><%= @post.title %></li>
    </ol>
        <h3><%= @post.title %></h3>
        <% if user_signed_in? %>
          <% if current_user.id == @post.user_id || current_user.role_id == 4 %>
            <div class="edit-post">
              <%= link_to edit_post_path(@post), class: "edit-post btn btn-primary btn-xs" do %>
                <span><i class="fa fa-pencil-square-o"></i> Edit post</span>
              <% end %>
              <%= link_to @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" do %>
                <i class="fa fa-lg fa-times-circle-o"></i> Delete
              <% end %>
            </div>
          <% end %>
        <% end %>
    <hr>
    <p>
      <strong>Contract:</strong>
      <%= @post.post_type %>
      | Posted on <%= @post.created_at.strftime("%d-%m-%Y") %>
    </p>
    <div class="row show-post-wrapper">
      <div class="col-md-8">
        <div class="post-show-slider">
          <ul class="bxslider">
            <% @post.photos.each do |photo| %>
              <li>
                <%= image_tag photo.image.url %>
              </li>
            <% end %>
          </ul>
          <div id="bx-pager">
            <% 
              $i = 0;
              @post.photos.each do |thumb|
            %>
              <a data-slide-index="<%= $i %>" href=""><%= image_tag thumb.image.url(:thumb) %></a>
            <%
                  $i +=1
              end
            %>  
          </div>
        </div>
        
        <div class="profile-info">
          <div class="panel panel-primary">
            <div class="panel-heading">
              Contact Info
            </div>
            <div class="panel-body">
              <% @profile =  @post.user.profile %>
              <ul>
                <li><i class="fa fa-user"></i> <%= @profile.first_name.present? ? @profile.first_name : "N/A" %></li>
                <li><i class="fa fa-phone"></i> <%= @profile.phone.present? ? @profile.phone : "N/A" %></li>
                <li><i class="fa fa-envelope"></i> <%= @profile.email.present? ? @profile.email : "N/A" %></li>
              </ul>
            </div>
          </div>  
        </div>
        <div class="post-show-amentity">
          <h3>Property amentites</h3>
          <hr>
          <ul class="row">
           <% @post_amentities.each do |str_amentity| %>
            <% amentity = str_amentity.to_i %>
            <% if amentity > 0 %>
              <li class="col-xs-6">
                <i class="fa fa-check"></i>
                <%= Amentity.find(amentity).name %>
              </li>
            <% end %>
          <% end %>
          </ul>
        </div>
        <div class="post-show-detail">
          <h3>Porperty Details</h3>
          <hr>
          <p>Price: <span class="btn btn-xs btn-danger">$ <%= @post.price %></span></p>
          <p>Address: <%= @post.address + " " + @post.area + ", " + @post.location.name %></p>
          <p>
            <% if @post.bedroom.present? %>
            <i class="fa fa-bed"></i> 
            <%= "Bedroom: " + @post.bedroom.to_s %>
            <% end %>
            <% if @post.bathroom.present? %>
            <%= "Bathroom: " + @post.bathroom.to_s %>
            <% end %>
            <% if @post.floor.present? %>
            <%= "Floor: " + @post.floor.to_s %>
            <% end %>
          </p>
          <p>
            <%= @post.description %>
          </p>
        </div>
      </div>
      <div class="recent-post col-md-4">
        <h3>Most Recent Posts</h3>
        <hr>
        <% @posts.each do |recent_post| %>
          <div class="post-box">
            <div class="img-container">
              <%= link_to recent_post do %>
                <%= image_tag recent_post.image.url(:medium), class: "img-responsive" %>
              <% end %>
            </div>
            <hr>
            <div class="post-text">
              <p class="post-title">
                <% $title = truncate(recent_post.title, length: 50) %>
                <%= link_to $title , recent_post %>
              </p>
              <div class="wrapper-text clearfix">
                <div class="left-box">
                  <span class="label label-success"><%= recent_post.post_type.capitalize %></span> 
                  <span class="date label label-primary"><i class="fa fa-clock-o"></i> <%= recent_post.created_at.strftime("%b / %d") %></span> 
                </div>
                <div class="right-box">
                  <span class="money label label-danger"><i class="fa fa-usd"></i> <%= recent_post.price %></span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    
  </div>
</div>