config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root to: "posts#index"
  resources :users, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :locations
  resources :property_types

end

app/views/layouts/_footer.html.erb
<footer>
	<hr>
	<div class="container">
		<div class="text-muted">&copy; 2016 by CMR-KH</div>
	</div>
</footer>

app/views/layouts/_nav.html.erb
<header class="container-fluid">
  <div class="header-logo">
    <%= image_tag "logo.png" %>
  </div>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
          <span class="icon-bar"></span>
        </button>
        <%= link_to "MRC Kh", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Sale", "#" %></li>
          <li><%= link_to "Buy", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Location <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @location = Location.all %>
              <% @location.each do |location| %>
              <li><%= link_to location.name, location_path(location) %></li>
              <% end %>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Property Type <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @location = PropertyType.all %>
              <% @location.each do |property| %>
              <li><%= link_to property.property_name, property_type_path(property) %></li>
              <% end %>
            </ul>
          </li>

          <% if user_signed_in? && current_user.role_id == 4 %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">View all <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "locations", locations_path %></li>
                <li><%= link_to "users", users_path %></li>
                <li><%= link_to "property types", property_types_path %></li>
              </ul>
            </li>
          <% end %>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to new_post_path do %>
                <i class="fa fa-plus-circle"></i> Add post
              <% end %>
            </li>
            <li><%= link_to current_user.username.capitalize, profile_path(current_user.id) if current_user.present? %></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
          <% else %>
            <li><%= link_to('Sign Up', new_user_registration_path)  %>  </li>
            <li><%= link_to('Login', new_user_session_path)  %>  </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_slider.html.erb
<ul class="bxslider">
	<li><%= image_tag "slider_01.jpg" %></li>
	<li><%= image_tag "slider_02.jpg" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "CMR-KH" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
  <% if notice %>
    <p class="alert alert-success" id="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger" id="alert"><%= alert %></p>
  <% end %>
</div>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>